# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target 'Laendleimmo' do
pod 'SVPullToRefresh'
pod 'UIActivityIndicator-for-SDWebImage'
end

target 'LaendleimmoTests' do

end

